name: ShopSystem
author: gyuriX
api-version: 1.13
main: gyurix.shopsystem.ShopSystem
version: 1.0
depend: [ WorldEdit, ColiseumGames, HuntingGames, TimedTrials, WRLDPaymentsAPI ]
commands:
  quit:
    aliases: [ l, leave ]
  join:
    aliases: [ play ]
  shop:
    aliases: [ buy ]
