name: ColiseumGames
author: gyuriX
api-version: 1.13
main: gyurix.coliseumgames.CGPlugin
version: 1.0
softdepend: [ WRLDPaymentsAPI ]
depend: [ WorldEdit, PartySystem, LevelingSystem ]
commands:
  coliseum:

